# Settings to generate the application frontend container.
FROM node:18.14.0

WORKDIR /app/frontend

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]