# Settings to generate the application backtend container.
FROM node:18.14.0

# Step-by-step installation of Sqlite dependencies.
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

COPY backend/package.json backend/package-lock.json ./

RUN npm install

COPY backend .

# Construction of the sqlite database.
RUN npm rebuild sqlite3

EXPOSE 3001

CMD ["npm", "start"]